services:
  snort:
    build: .
    container_name: snort
    ports:
      - "8000:8000"
#    volumes:
#      - ./Thursday-WorkingHours.pcap:/root/snort/test.pcap
    depends_on:
      - db
  db:
    image: postgres:14
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    container_name: db