services:
  snort:
    build: .
    container_name: snort
    ports:
      - "8000:8000"
#    volumes:
#      - ./Thursday-WorkingHours.pcap:/root/snort/test.pcap
    depends_on:
      - db
  front:
    build: snort-front
    container_name: front
    ports:
      - "8080:80"
  db:
    image: postgres:14
    ports:
      - "5433:5432"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    container_name: db

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8888:8080"
    volumes:
      - ./openapi.yaml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml
